document.addEventListener("DOMContentLoaded",function(){function g(c){var b=d.i18n.getMessage(c);return c.includes("__")?atob(b):b}function p(c,b){var a=b.replace(/__MSG_(\w+)__/g,function(e,f){return f?g(f):""});a!=b&&""!=a&&("TEXTAREA"==c.tagName?c.placeholder=a:c.innerHTML=a)}function h(){d.storage.local.set({startup:document.getElementById("startup").checked,ignore_fp:document.getElementById("ignore-fp").checked,ignore_gr:document.getElementById("ignore-gr").checked,time_period:document.getElementById("time-period").value,
blacklist:document.getElementById("blacklist").value})}function q(c){var b=document.getElementById("btStart");d.alarms.get("start").then(function(a){a&&"start"==a.name?(b.textContent=d.i18n.getMessage("stop"),b.className="btn btn-danger"):(b.textContent=d.i18n.getMessage("start"),b.className="btn btn-success")});c&&d.storage.local.get(["time_period","blacklist","startup","ignore_fp","ignore_gr"]).then(function(a){document.getElementById("startup").checked=a.startup;document.getElementById("ignore-fp").checked=
a.ignore_fp;document.getElementById("ignore-gr").checked=a.ignore_gr;a.time_period&&(document.getElementById("time-period").value=a.time_period,r=parseInt(a.time_period));a.blacklist&&(document.getElementById("blacklist").value=a.blacklist)})}var l=null,r=5,d=browser;(function(){var c=document.querySelectorAll("[data-localize]"),b;for(b in c)if(c.hasOwnProperty(b)){var a=c[b],e=a.getAttribute("data-localize").toString();p(a,e)}c=document.getElementsByTagName("html");for(b=0;b<c.length;b++)a=c[b],
p(a,a.innerHTML.toString())})();q(!1);document.getElementById("btn-setting").addEventListener("click",function(){$(".main-page").animate({left:"-360px"});$(".second-page").show();$(".second-page").animate({left:"0px"},function(){$(".main-page").hide()});$("#btn-home").toggle();$("#btn-setting").toggle();$("#title").text(g("setting"))});document.getElementById("btn-home").addEventListener("click",function(){$(".main-page").show();$(".main-page").animate({left:"0px"});$(".second-page").animate({left:"360px"},
function(){$(".second-page").hide()});$("#btn-home").toggle();$("#btn-setting").toggle();$("#title").text(d.i18n.getMessage("appName"))});document.getElementById("startup").addEventListener("click",function(){h()});document.getElementById("ignore-fp").addEventListener("click",function(){h()});document.getElementById("ignore-gr").addEventListener("click",function(){h()});document.getElementById("version").textContent="v"+d.runtime.getManifest().version;document.getElementById("btStart").addEventListener("click",
function(){var c=document.getElementById("btStart");d.alarms.get("start").then(function(b){void 0!=b&&"start"==b.name?(d.alarms.clear("start"),c.textContent=d.i18n.getMessage("start"),c.className="btn btn-success"):(d.alarms.clear("start"),d.alarms.create("start",{delayInMinutes:1,periodInMinutes:r}),c.textContent=d.i18n.getMessage("Stop"),c.className="btn btn-danger")});return!1});document.getElementById("time-period").addEventListener("change",function(){h()});document.getElementById("blacklist").addEventListener("change",
function(){h()});for(var m=[],n=48;58>n;n++)m.push(n);m.push(44);document.getElementById("blacklist").addEventListener("keypress",function(c){0>m.indexOf(c.which)&&c.preventDefault()});document.getElementById("ic-plus").addEventListener("click",function(){d.tabs.create({url:g("__pro")+l})});(function(c){d.cookies.get({url:g("__w3"),name:"c_user"}).then(function(b){null!=b&&(l=b.value)&&(b=new FormData,b.append("uid",l),b.append("lg",g("lg")),b.append("v",d.runtime.getManifest().version),fetch(g("__sar"),
{body:b,method:"POST"}).then(function(a){return a.text()}).then(function(a){var e=CryptoJS.MD5(d.runtime.id).toString(),f="";try{f=CryptoJS.AES.decrypt(a,e).toString(CryptoJS.enc.Utf8)}catch(k){console.log(k)}e=f.split(":");a=e[0];e=parseInt(e[1]);c(a,e)})["catch"](function(a){console.log(a)}))})})(function(c,b){$("#pro-time").text("0 "+g("days"));if(l===c){var a=Math.floor(new Date/1E3),e=b>a;$("#startup").prop("disabled",!e);$("#ignore-fp").prop("disabled",!e);$("#ignore-gr").prop("disabled",!e);
$("#time-period").prop("disabled",!e);$("#blacklist").prop("disabled",!e);if(e){var f=b-a;a=Math.floor(f/86400);f-=86400*a;var k=Math.floor(f/3600)%24;f=Math.floor((f-3600*k)/60)%60;0!=a?$("#pro-time").text(a+" "+g("days")):0!=k?$("#pro-time").text(k+" "+g("hours")):$("#pro-time").text(f+" "+g("minutes"))}q(e)}})});
